CREATE INDEX delta_task_searchable_compound_workflow_created_date_time ON delta_task (wfs_searchable_compound_workflow_created_date_time);
CREATE INDEX delta_task_searchable_compound_workflow_started_date_time ON delta_task (wfs_searchable_compound_workflow_started_date_time);
CREATE INDEX delta_task_searchable_compound_workflow_stopped_date_time ON delta_task (wfs_searchable_compound_workflow_stopped_date_time);
CREATE INDEX delta_task_searchable_compound_workflow_finished_date_time ON delta_task (wfs_searchable_compound_workflow_finished_date_time);