
package ee.webmedia.mso;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Mso", targetNamespace = "http://webmedia.ee/mso")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Mso {


    /**
     * 
     * @param msoDocumentInput
     * @return
     *     returns ee.webmedia.mso.MsoPdfOutput
     */
    @WebMethod
    @WebResult(name = "msoPdfOutput", targetNamespace = "")
    @RequestWrapper(localName = "convertToPdf", targetNamespace = "http://webmedia.ee/mso", className = "ee.webmedia.mso.ConvertToPdf")
    @ResponseWrapper(localName = "convertToPdfResponse", targetNamespace = "http://webmedia.ee/mso", className = "ee.webmedia.mso.ConvertToPdfResponse")
    public MsoPdfOutput convertToPdf(
        @WebParam(name = "msoDocumentInput", targetNamespace = "")
        MsoDocumentInput msoDocumentInput);

    /**
     * 
     * @param msoDocumentAndFormulasInput
     * @return
     *     returns ee.webmedia.mso.MsoDocumentOutput
     */
    @WebMethod
    @WebResult(name = "msoDocumentOutput", targetNamespace = "")
    @RequestWrapper(localName = "replaceFormulas", targetNamespace = "http://webmedia.ee/mso", className = "ee.webmedia.mso.ReplaceFormulas")
    @ResponseWrapper(localName = "replaceFormulasResponse", targetNamespace = "http://webmedia.ee/mso", className = "ee.webmedia.mso.ReplaceFormulasResponse")
    public MsoDocumentOutput replaceFormulas(
        @WebParam(name = "msoDocumentAndFormulasInput", targetNamespace = "")
        MsoDocumentAndFormulasInput msoDocumentAndFormulasInput);

    /**
     * 
     * @param msoDocumentAndFormulasInput
     * @return
     *     returns ee.webmedia.mso.MsoDocumentAndPdfOutput
     */
    @WebMethod
    @WebResult(name = "msoDocumentAndPdfOutput", targetNamespace = "")
    @RequestWrapper(localName = "replaceFormulasAndConvertToPdf", targetNamespace = "http://webmedia.ee/mso", className = "ee.webmedia.mso.ReplaceFormulasAndConvertToPdf")
    @ResponseWrapper(localName = "replaceFormulasAndConvertToPdfResponse", targetNamespace = "http://webmedia.ee/mso", className = "ee.webmedia.mso.ReplaceFormulasAndConvertToPdfResponse")
    public MsoDocumentAndPdfOutput replaceFormulasAndConvertToPdf(
        @WebParam(name = "msoDocumentAndFormulasInput", targetNamespace = "")
        MsoDocumentAndFormulasInput msoDocumentAndFormulasInput);

}
