
package ee.webmedia.mso;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Mso", targetNamespace = "http://webmedia.ee/mso")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Mso {


    /**
     * 
     * @param msoInput
     * @return
     *     returns ee.webmedia.mso.MsoOutput
     */
    @WebMethod
    @WebResult(name = "msoOutput", targetNamespace = "")
    @RequestWrapper(localName = "convertToPdf", targetNamespace = "http://webmedia.ee/mso", className = "ee.webmedia.mso.ConvertToPdf")
    @ResponseWrapper(localName = "convertToPdfResponse", targetNamespace = "http://webmedia.ee/mso", className = "ee.webmedia.mso.ConvertToPdfResponse")
    public MsoOutput convertToPdf(
        @WebParam(name = "msoInput", targetNamespace = "")
        MsoInput msoInput);

}
