
package ee.webmedia.alfresco.adr;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AvalikDokumendiRegister", targetNamespace = "http://alfresco/avalikdokumendiregister")
public interface AvalikDokumendiRegister {

    /**
     * 
     * @param parameters
     * @return
     *     returns ee.webmedia.alfresco.adr.OtsiDokumendidResponse
     */
    @WebMethod
    @WebResult(name = "dokument", targetNamespace = "http://alfresco/avalikdokumendiregister")
    @RequestWrapper(localName = "otsiDokumendid", targetNamespace = "http://alfresco/avalikdokumendiregister", className = "ee.webmedia.alfresco.adr.OtsiDokumendid")
    @ResponseWrapper(localName = "otsiDokumendidResponse", targetNamespace = "http://alfresco/avalikdokumendiregister", className = "ee.webmedia.alfresco.adr.OtsiDokumendidResponse")
    public List<Dokument> otsiDokumendid(
        @WebParam(name = "perioodiAlgusKuupaev", targetNamespace = "http://alfresco/avalikdokumendiregister")
        XMLGregorianCalendar perioodiAlgusKuupaev,
        @WebParam(name = "perioodiLoppKuupaev", targetNamespace = "http://alfresco/avalikdokumendiregister")
        XMLGregorianCalendar perioodiLoppKuupaev,
        @WebParam(name = "dokumendiLiik", targetNamespace = "http://alfresco/avalikdokumendiregister")
        String dokumendiLiik,
        @WebParam(name = "otsingusona", targetNamespace = "http://alfresco/avalikdokumendiregister")
        String otsingusona);

    /**
     * 
     * @param parameters
     * @return
     *     returns ee.webmedia.alfresco.adr.OtsiDokumentDetailidegaResponse
     */
    @WebMethod
    @WebResult(name = "dokumentDetailidega", targetNamespace = "http://alfresco/avalikdokumendiregister")
    @RequestWrapper(localName = "otsiDokumentDetailidega", targetNamespace = "http://alfresco/avalikdokumendiregister", className = "ee.webmedia.alfresco.adr.OtsiDokumentDetailidega")
    @ResponseWrapper(localName = "otsiDokumentDetailidegaResponse", targetNamespace = "http://alfresco/avalikdokumendiregister", className = "ee.webmedia.alfresco.adr.OtsiDokumentDetailidegaResponse")
    public DokumentDetailidega dokumentDetailidega(
            @WebParam(name = "viit", targetNamespace = "http://alfresco/avalikdokumendiregister")
            String viit,
            @WebParam(name = "registreerimiseAeg", targetNamespace = "http://alfresco/avalikdokumendiregister")
            XMLGregorianCalendar registreerimiseAeg);

    /**
     * 
     * @param parameters
     * @return
     *     returns ee.webmedia.alfresco.adr.OtsiFailSisugaResponse
     */
    @WebMethod
    @WebResult(name = "fail", targetNamespace = "http://alfresco/avalikdokumendiregister")
    @RequestWrapper(localName = "otsiFailSisuga", targetNamespace = "http://alfresco/avalikdokumendiregister", className = "ee.webmedia.alfresco.adr.OtsiFailSisuga")
    @ResponseWrapper(localName = "otsiFailSisugaResponse", targetNamespace = "http://alfresco/avalikdokumendiregister", className = "ee.webmedia.alfresco.adr.OtsiFailSisugaResponse")
    public Fail failSisuga(
            @WebParam(name = "viit", targetNamespace = "http://alfresco/avalikdokumendiregister")
            String viit,
            @WebParam(name = "registreerimiseAeg", targetNamespace = "http://alfresco/avalikdokumendiregister")
            XMLGregorianCalendar registreerimiseAeg,
            @WebParam(name = "failinimi", targetNamespace = "http://alfresco/avalikdokumendiregister")
            String filename);

    @WebMethod
    @WebResult(name = "dokumendiliik", targetNamespace = "http://alfresco/avalikdokumendiregister")
    @RequestWrapper(localName = "otsiDokumendiliigid", targetNamespace = "http://alfresco/avalikdokumendiregister", className = "ee.webmedia.alfresco.adr.OtsiDokumendiliigid")
    @ResponseWrapper(localName = "otsiDokumendiliigidResponse", targetNamespace = "http://alfresco/avalikdokumendiregister", className = "ee.webmedia.alfresco.adr.OtsiDokumendiliigidResponse")
    public List<Dokumendiliik> dokumendiliigid();

    @WebMethod
    @WebResult(name = "dokumentDetailidegaFailSisuga", targetNamespace = "http://alfresco/avalikdokumendiregister")
    @RequestWrapper(localName = "koikDokumendidLisatudMuudetud", targetNamespace = "http://alfresco/avalikdokumendiregister", className = "ee.webmedia.alfresco.adr.KoikDokumendidLisatudMuudetud")
    @ResponseWrapper(localName = "koikDokumendidLisatudMuudetudResponse", targetNamespace = "http://alfresco/avalikdokumendiregister", className = "ee.webmedia.alfresco.adr.KoikDokumendidLisatudMuudetudResponse")
    public List<DokumentDetailidega> koikDokumendidLisatudMuudetud(
            @WebParam(name = "perioodiAlgusKuupaev", targetNamespace = "http://alfresco/avalikdokumendiregister")
            XMLGregorianCalendar perioodiAlgusKuupaev,
            @WebParam(name = "perioodiLoppKuupaev", targetNamespace = "http://alfresco/avalikdokumendiregister")
            XMLGregorianCalendar perioodiLoppKuupaev);

    @WebMethod
    @WebResult(name = "dokumentKustutatud", targetNamespace = "http://alfresco/avalikdokumendiregister")
    @RequestWrapper(localName = "koikDokumendidKustutatud", targetNamespace = "http://alfresco/avalikdokumendiregister", className = "ee.webmedia.alfresco.adr.KoikDokumendidKustutatud")
    @ResponseWrapper(localName = "koikDokumendidKustutatudResponse", targetNamespace = "http://alfresco/avalikdokumendiregister", className = "ee.webmedia.alfresco.adr.KoikDokumendidKustutatudResponse")
    public List<Dokument> koikDokumendidKustutatud(
            @WebParam(name = "perioodiAlgusKuupaev", targetNamespace = "http://alfresco/avalikdokumendiregister")
            XMLGregorianCalendar perioodiAlgusKuupaev,
            @WebParam(name = "perioodiLoppKuupaev", targetNamespace = "http://alfresco/avalikdokumendiregister")
            XMLGregorianCalendar perioodiLoppKuupaev);

}
