
package ee.webmedia.ocr;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Ocr", targetNamespace = "http://webmedia.ee/ocr")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Ocr {


    /**
     * 
     * @param ocrInput
     * @return
     *     returns ee.webmedia.ocr.OcrOutput
     */
    @WebMethod
    @WebResult(name = "ocrOutput", targetNamespace = "")
    @RequestWrapper(localName = "convertToPdf", targetNamespace = "http://webmedia.ee/ocr", className = "ee.webmedia.ocr.ConvertToPdf")
    @ResponseWrapper(localName = "convertToPdfResponse", targetNamespace = "http://webmedia.ee/ocr", className = "ee.webmedia.ocr.ConvertToPdfResponse")
    public OcrOutput convertToPdf(
        @WebParam(name = "ocrInput", targetNamespace = "")
        OcrInput ocrInput);

}
