DROP TABLE IF EXISTS imp_d_menetlus;
DROP TABLE IF EXISTS imp_d_dok_men;
DROP TABLE IF EXISTS imp_d_dok_men2;
DROP TABLE IF EXISTS imp_d_isik_men;
DROP TABLE IF EXISTS imp_d_kommentaar;
DROP TABLE IF EXISTS imp_d_lisavaljavaartus;
DROP TABLE IF EXISTS imp_resolutsioonid;
DROP TABLE IF EXISTS imp_d_kasut_ostr;
DROP TABLE IF EXISTS imp_d_kasut_adsi;
DROP TABLE IF EXISTS imp_completed_docs;
DROP TABLE IF EXISTS imp_completed_docs2;
DROP TABLE IF EXISTS imp_delta_users;
DROP TABLE IF EXISTS imp_casefile;
DROP TABLE IF EXISTS imp_compound_workflow;
DROP TABLE IF EXISTS imp_workflow;
DROP TABLE IF EXISTS imp_task;
DROP TABLE IF EXISTS imp_association; 
DROP TABLE IF EXISTS imp_completed_procedures;
DROP TABLE IF EXISTS imp_failed_procedures;
DROP TABLE IF EXISTS imp_error_code;
DROP TABLE IF EXISTS imp_task1;
DROP TABLE IF EXISTS imp_task2;
DROP TABLE IF EXISTS imp_task3;

--Functions
DROP FUNCTION IF EXISTS imp_create_indexs();
DROP FUNCTION IF EXISTS imp_get_comment(in_id integer, in_menetluseliik character varying, in_tahtaegkp timestamp with time zone, in_prioriteet character varying, in_labibkantselei boolean, in_trykk boolean);
DROP FUNCTION IF EXISTS imp_get_string(in_string character varying);
DROP FUNCTION IF EXISTS imp_insert_failed(in_procedure_id integer, in_started_date_time timestamp with time zone, in_finished_date_time timestamp with time zone, in_task_user character varying, in_error_code character varying, in_error_msg character varying);
DROP FUNCTION IF EXISTS imp_proc(in_default_owner_id character varying, in_number_of_casefile bigint);