#!/bin/sh
set -eu

<<<<<<< HEAD
# @author Alar Kvell

=======
>>>>>>> develop-5.1
cd "$(dirname $0)"
fgrep '.html' ../../source/java/ee/webmedia/alfresco/notification/model/notification-messages_et_EE.properties|sed -e 's/.*=//' -e 's/\\u00F5/õ/g' -e 's/\\u00E4/ä/g' -e 's/\\u00F6/ö/g' -e 's/\\u00FC/ü/g' > system-templates.txt
dos2unix -q system-templates.txt
sort system-templates.txt > system-templates-sorted.txt

out="../../source/java/ee/webmedia/alfresco/workflow/bootstrap/testWorkflowTemplates.xml"
echo '<?xml version="1.0" encoding="UTF-8"?>' >"${out}"
echo '<view:view xmlns:view="http://www.alfresco.org/view/repository/1.0" xmlns:cm="http://www.alfresco.org/model/content/1.0" xmlns:app="http://www.alfresco.org/model/application/1.0"' >>"${out}"
echo '   xmlns:sys="http://www.alfresco.org/model/system/1.0" xmlns:docTempl="http://alfresco.webmedia.ee/model/document-template/1.0">' >>"${out}"
echo '' >>"${out}"
echo "   <!-- This file was generated by common/etc/system-templates.sh -->" >>"${out}"

IFS="
"
for i in $(cat system-templates-sorted.txt)
do
	echo '' >>"${out}"
	echo "   <cm:content view:childName=\"cm:${i}\">" >>"${out}"
	echo '      <view:aspects>' >>"${out}"
	echo '         <docTempl:template />' >>"${out}"
	echo '         <docTempl:notificationTemplate />' >>"${out}"
	echo '      </view:aspects>' >>"${out}"
	echo '      <view:properties>' >>"${out}"
	echo '         <docTempl:templateType>NOTIFICATION_TEMPLATE</docTempl:templateType>' >>"${out}"
	echo '         <docTempl:comment>Süsteemne mall</docTempl:comment>' >>"${out}"
	echo "         <cm:name>${i}</cm:name>" >>"${out}"
	echo "         <docTempl:name>${i}</docTempl:name>" >>"${out}"
	echo '         <cm:content>contentUrl=classpath:ee/webmedia/alfresco/workflow/bootstrap/testWorkflowTemplate.html|mimetype=text/html|size=|encoding=UTF-8</cm:content>' >>"${out}"
	echo '      </view:properties>' >>"${out}"
	echo '   </cm:content>' >>"${out}"
done

echo '' >>"${out}"
echo '</view:view>' >>"${out}"

echo "Done"
exit 0
